apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: dramatiq-app-scaler
spec:
  scaleTargetRef:
    name: dramatiq-app
  minReplicaCount: 0
  maxReplicaCount: 10
  pollingInterval: 10
  cooldownPeriod: 30
  triggers:
    - type: rabbitmq
      metadata:
        protocol: http
        host: http://guest:guest@rmq.dramatiq:15672
        mode: QueueLength
        value: "1"
        queueName: default
        useRegex: "false"
