apiVersion: v1
kind: Service
metadata:
  name: rmq
spec:
  ports:
    - port: 5672
      targetPort: 5672
      name: rmq

    - port: 15672
      targetPort: 15672
      name: rmq-management
  selector:
    app: rmq
