apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: pull-secret
spec:
  encryptedData:
    .dockerconfigjson: AgBYDg6IGI5R2ftZIoDaWwzFnhp1Iufn9biqmsSsiMTeGV+idmdxQrUy3r04rcKnQ9KSFHrWWOpnldNntBNh6gim23lYXkz1O9whlSrPBgbKsMSU0gWHAEl3gr8o0d8uNEbbxhGsHjI5Ge0zdutkP0yG/4Y5L99XuyZ7KxTbiXpp87xC8PD2pisJFac+isZOVoTpBZbhJhc34QZ2P1svqaeZ9v/BoobPssKa/Rjuex2TvangkLrPQGD+gVjAj0Ql3gFR0dLWVWy5qhaIJdqOy0iQLyQvf5onExDeUOMK7ojd5wVQpVDZWVrqZhiXuV+Jv17l04isLIYYJ1eZSFY7XfcpjiZAv78v3EC9tLUITr6V1ile34exWg4TZDSbzJ2Hs3AWQcwv0frgC1s48XM7JCVUaMQ7eIIn3yPlGJNB46YlqxUPQBiarW++e0vqEtRL+4IMvDyEOKY0kXgF9P5S11pnzT8FtEnYpY8Hje/2Upu/IpXlTD6AZKzDJk0a1FVn4KxukwCPv8BlTw+Rbx6ATvfgdfX3jdo0BNll1IoMiTKx4AO2BOg87keyhUmQJiaUQx3GZ5N+RdSZzr2PIFa9c+4F4gUK2Ecqbde3cZP2viS5TwqJaKFbDEU4g5cswEUcUTjr7phLAkDfvSws+MezANoUWhY65Swb1RjZSNeF6gp9XQA55N0+ilZ8ZkiBoF3D7WlmsRjDAJBoEGAvGlCyDn1G5Ppny8Hl09AI+PYfpeBywV6o1esEr0WPE+ASeMQBHUo0dw+SnASUmis39w1R0aN7zZ2saPHvL3Owmk2bmdo4d5ZaSCs7qBl40mgy+nzbjoytJt++jgdQqstzyhoWhKq7dIBoxtiPY9X0d6t0Mao7OVvfet4o2qOGUFZJHRuELR+0VRlrKcgXetmVcg5RldjnJz6HKYAnF3fgLznUVRqfGQaBFcNkXV5NDKM1PqhRdTIPshrqupctgrx50XDqiKKOgp6JIfNunrA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: pull-secret
    type: kubernetes.io/dockerconfigjson
