services:
  rmq:
    image: public.ecr.aws/docker/library/rabbitmq:4.2.0-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics status"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
